### ISSUE TITLE
(Uiteindelijke) 3D-prints hierin toevoegen

### ISSUE THREAD

**Issue by yochem** [3PMAP/3dprints#1]
Ik denk dat het handig is om in deze repository de 3d-prints te hebben. Maar bijvoorbeeld ook dingen als een `changelog` (logboek waar je alle veranderingen kort in omschrijft) en bijv. een screenshot (`.jpg`)

**Comment by jelle641** [comment]
Ik denk dat chancelogs wel een goed idee is. Daarin beschrijven we even kort wat er is veranderd zodat mensen ook makkelijker kunnen bijhouden welke progressie we maken. Ik denk dat het slimmer is als we daar vanaf nu mee beginnen, en niet vanaf het eerste idee alle veranderingen gaan beschrijven (of iemand moet daar veel zin in hebben natuurlijk)
