### ISSUE TITLE
Structuur

### ISSUE THREAD

**Issue by yochem** [3PMAP/3dprints#2]
Misschien in deze structuur?
```
.
├── images
|   ├── palm-v5.jpeg
|   └── vinger-v1.jpeg
├── palm-v5.stl
├── vinger-v1.stl
├── duim-v10.stl
├── LICENSE
└── README.md
```
😄

**Comment by jelle641** [comment]
Waarom een .stl bestand, en een .jpeg bestand?
Het kan wel maar de .stl bestanden opent github ook waardoor je het ontwerp kan zien

**Comment by yochem** [comment]
Ohja, zie t nu. Dan is t niet nodig 😊
