### ISSUE TITLE
Transparant materiaal?

### ISSUE THREAD

**Issue by jelle641** [3PMAP/3dprints#3]
https://www.123-3d.nl/123-3D-Filament-transparant-1-75-mm-Nylon-0-5-kg-Jupiter-serie-123-3D-huismerk-i1952-t12876.html

Werkt dit met de 3D printer? Hoe denkt u dat het er uit gaat zien?
@moorlag

**Comment by moorlag** [comment]
Let even goed op de temperatuur. 
Te warm = bad 
Te koud = bad
